# Generated by Django 2.2.6 on 2019-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_userprofiles_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='address',
        ),
    ]
