# Generated by Django 2.2.6 on 2019-11-14 10:22

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_remove_userprofiles_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=25, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('heading2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'feature',
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='FooterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'FooterImage',
                'db_table': 'footerimage',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=25, null=True)),
                ('recipe_image', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('step', ckeditor.fields.RichTextField(null=True)),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=25, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'db_table': 'recipe',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='')),
                ('slider_caption1', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_caption2', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_caption3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'db_table': 'slider',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, max_length=30, null=True)),
                ('social_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
                'db_table': 'social_links',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(default='0', max_length=25)),
                ('receipe_name', models.ManyToManyField(blank=True, null=True, related_name='food', to='blog_api.Recipe')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=25, null=True)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='blog_api.Feature')),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
                'db_table': 'aboutus',
            },
        ),
    ]
