# Generated by Django 2.2.6 on 2019-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_aboutus_feature_footerimage_ingredients_recipe_slider_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='receipe_name',
            field=models.ManyToManyField(related_name='food', to='blog_api.Recipe'),
        ),
    ]
