# Generated by Django 2.2.6 on 2019-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_subject', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_msg', models.TextField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'db_table': 'contact',
            },
        ),
    ]
