# Generated by Django 2.2.6 on 2019-11-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='receipe_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default='0', max_length=25, to='blog_api.Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
