# Generated by Django 2.2.6 on 2019-11-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0011_auto_20191119_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='receipe_name',
            new_name='recipename',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.AddField(
            model_name='rating',
            name='recipeimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rimage', to='blog_api.Recipe'),
        ),
    ]
