# Generated by Django 2.2.6 on 2019-11-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0012_auto_20191119_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
    ]
