# Generated by Django 2.2.6 on 2019-11-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0013_remove_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
