# Generated by Django 2.2.6 on 2019-11-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0014_auto_20191120_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rate',
        ),
    ]
