# Generated by Django 2.2.6 on 2019-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0015_auto_20191120_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipeimage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
