# Generated by Django 2.2.6 on 2019-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0016_auto_20191120_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
