# Generated by Django 2.2.6 on 2019-11-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0017_rating_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Detail'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='recipeimage',
        ),
        migrations.AlterField(
            model_name='comments',
            name='receipe_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_recipename', to='blog_api.Recipe'),
        ),
    ]
